### ISSUE TITLE
Error Fetch

### ISSUE THREAD

**Issue by Saykide** [xJackSx/BSPWMparrot#6]
"ens33: error fetch"
en la barra superior izquierda al lado derecho de la fecha me aparece eso

**Comment by MarcOrfilaCarreras** [comment]
Buenas @Saykide,
Esto generalmente apunta a un problema con la interfaz que el script `ethernet_status.sh` está utilizando.

Mi sugerencia sería ajustar el script `ethernet_status.sh` para que use la interfaz correcta. Puede que necesites verificar si 'ens33' es la interfaz correcta para tu configuración o hacer las modificaciones necesarias para que coincida con la interfaz que deseas monitorear.

**Comment by xJackSx** [comment]
Buenas,

1.- Es importante que si utilizan el script de Parrot para Kali es claro
que les de algún problema con esos módulos, de igual manera a la inversa.

2.- Es un script desarrollado especialmente para máquinas virtuales VMware,
si utilizan VitualBox o cualquier otra plataforma de virtualizacion,
también generará estos problemas.

3.- Antes de utilizar este tipo de herramientas es importante que tengas
las nociones básicas de cada configuración, al igual de conceptos básicos
de linux.

Espero haber sido claro.

Saludos.

**Comment by Saykide** [comment]
tendria que haber cerrado esto jaja, el mismo dia que lo pregunte logre resolverlo era cambiando una configuracion de esa barra que no me acuerdo como se llama, entre a ifconfig me fije como se llamaba mi red lo cambie por ese y arreglado
